@Library("shared-library") _
pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkoutManager()
            }
        }
        stage('Build') {
             steps {
                 buildManager()
        
             }
        }
        stage('UnitTest') {
             steps {
                 unittestManager()
        
             }
        }
        stage('IntegrationTest') {
             steps {
                 integrationtestManager()
        
             }
        }
        stage('Deploy') {
             steps {
                 deployManager()
        
             }
        }
    }
}
