@Library("shared-library") _
pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                helloWorld()
            }
        }
        stage('Greeting') {
             steps {
                 greetingAll()
             }
        }
    }
}
